### ISSUE TITLE
Advice on LICESE

### ISSUE THREAD

**Issue by tisonkun** [whatis-geb/operation#2]
内容专门的许可协议，类似 GPL 的效果的话，叫做 CC-BY（署名）-SA（同类分享），看情况可以加 NC （非商业使用）条款。

See also https://creativecommons.org/licenses/by-sa/4.0/, and https://creativecommons.org/licenses/by-nc-sa/4.0/.

**Comment by QingZ11** [comment]
嗯，内容还是用知识共享协议来得好。谢谢 tison
